definitions:
  entities.User:
    properties:
      PK:
        type: string
      SK:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  handlers.errorResponse:
    properties:
      error:
        type: string
    type: object
  handlers.userResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/entities.User'
        type: array
    type: object
info:
  contact: {}
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Get all users from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.userResponse'
      summary: Get all users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entities.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entities.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorResponse'
      security:
      - apiKeyAuth: []
      summary: Create a new user
      tags:
      - Users
swagger: "2.0"
