definitions:
  entities.User:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
  handlers.errorResponse:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entities.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entities.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorResponse'
      security:
      - apiKeyAuth: []
      summary: Create a new user
      tags:
      - Users
swagger: "2.0"
